# will change after pushing to the github.com
token: "723697778:AAFboITXpC-0dCAM2rmTRoH34Z5vOUV5HK4"

channelusername: "@dailyrock"

administrators:
  - 83919508
  - 94500506

tempdirectory: "./tmp"

# in seconds
tracker:
  interval: 5 
  default: 15